import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import { Toaster } from "@/components/ui/toaster"
import StoreProvider from "@/store/StoreProvider";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={jost.className}>
          <main> {children}</main>
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
